services:
  # PostgreSQL for Temporal
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    image: postgres:13
    networks:
      - temporal-network
    expose:
      - 5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Temporal Server
  temporal:
    container_name: temporal
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - ENABLE_ES=false
    image: temporalio/auto-setup:1.22.3
    networks:
      - temporal-network
    ports:
      - 7233:7233
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "workflow", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Temporal Web UI
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:latest
    networks:
      - temporal-network
    ports:
      - 8233:8080

  # Your Express Server
  app-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DB_HOST=34.47.157.61
      - DB_USER=admin
      - DB_PASSWORD=$$uperZop123
      - DB_NAME=superzop_delivery
      #- DB_PORT=3306
      - NODE_ENV=development
      - ORDERING_APP_BASE_URL=https://dev-services.superzop.com
      - TEMPORAL_TASK_QUEUE=superzop-sync-queue
      - NODE_OPTIONS=--max-old-space-size=512
    networks:
      - temporal-network
    depends_on:
      temporal:
        condition: service_healthy

  # Your Worker
  app-worker:
    build: .
    command: npm run worker
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DB_HOST=34.47.157.61
      - DB_USER=admin
      - DB_PASSWORD=$$uperZop123
      - DB_NAME=superzop_delivery
      #- DB_PORT=3306
      - NODE_ENV=development
      - ORDERING_APP_BASE_URL=https://dev-services.superzop.com
      - TEMPORAL_TASK_QUEUE=superzop-sync-queue
      - NODE_OPTIONS=--max-old-space-size=512
    networks:
      - temporal-network
    depends_on:
      temporal:
        condition: service_healthy

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  postgresql-data: