services:
  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DB=postgresql
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      - postgresql

  # Express Server
  app-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=$$uperZop123
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - NODE_ENV=${NODE_ENV}
      - ORDERING_APP_BASE_URL=${ORDERING_APP_BASE_URL}
    depends_on:
      - postgresql

  # Worker
  app-worker:
    build: .
    command: npm run worker
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=$$uperZop123
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - NODE_ENV=${NODE_ENV}
      - ORDERING_APP_BASE_URL=${ORDERING_APP_BASE_URL}
    depends_on:
      - postgresql

  # PostgreSQL for Temporal
  postgresql:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal

 